import datetime
from clickhouse_driver import Client
host= "offline-tech.ikunchi.com"
port = 43068
user = 'default'
password = 'Kunchi1234!@#$'
database= 'ads'
send_receive_timeout = 200
client = Client(host=host, port=port, user=user, password=password,database=database, send_receive_timeout = send_receive_timeout)

sql = client.execute("""truncate table dw.dw_t08_01_order_warehouse_out;""")
print("执行SQL时间：",datetime.datetime.now())
sql1 = client.execute("""insert into dw.dw_t08_01_order_warehouse_out
                       select
                        order_code,
                        source_code,
                        po,
                        business,
                        platform,
                        order_type,
                        order_type_sub,
                        org_no,
                        org_name,
                        source_stock_org_no,
                        source_stock_org_name,
                        source_logic_warehouse_no,
                        source_logic_warehouse_name,
                        source_logic_warehouse_attr,
                        source_nc_ext,warehouse_no,
                        warehouse_name,
                        target_stock_org_no,
                        target_stock_org_name,
                        target_logic_warehouse_no,
                        target_logic_warehouse_name,
                        target_nc_ext,
                        customer_no,
                        customer_name,
                        customer_warehouse_no,
                        customer_warehouse_name,
                        carrier_no,
                        carrier_name,
                        courier_no,
                        weight,
                        shop_no,
                        shop_name,
                        platform_order_code,
                        issue_party_name,
                        contact,
                        phone_no,
                        payment_method,
                        transaction_account,
                        invoice_type,
                        customer_desc,
                        sku_num,
                        total_num,
                        stock_out_num,
                        sign_in_num,
                        currency,
                        total_mny,
                        preferential_mny,
                        already_paid_mny,
                        payable_mny,
                        province,
                        city,
                        district,
                        address,
                        order_date,
                        expect_arrive_date,
                        required_delivery_date,
                        maker,
                        maker_dept,
                        approval_by,
                        approval_date,
                        descs,
                        reason,
                        flag,
                        state,
                        create_by,
                        create_date,
                        update_by,
                        update_date,
                        nc_info,
                        other_info,
                        business_unit,
                        postage,
                        owner_channel_code,
                        owner_channel_name,
                        stock_channel_code,
                        stock_channel_name,
                        business_unit_name,
                        update_time,
                        now()
                        from obc_order.order_warehouse_out a where create_date >= 1635681600*1000 order by a.create_date desc""")
print("执行SQL结束时间：",datetime.datetime.now())
